### ISSUE TITLE
could junkimage affect the rank1?

### ISSUE THREAD

**Issue by JoyLuo** [layumi/2016_person_re-ID#3]
respectable layumi:
  i am very interest in person re-id, and i read the paper and code from your team. and when i evaluation the result of net.  the njunk can improve the result of rank1,  and i think the real rank1 is `cmc(n:end)=1;` rather than `cmc(n-njunk:end) = 1;` 
 and i am looking forward to your reply.
and the code from  2016_person_re-ID/evaluation/compute_AP_rerank.m
`
if ~isempty(find(good_image == index(n), 1)) 
        cmc(n-njunk:end) = 1;
        flag = 1; % good image 
        good_now = good_now+1; 
end
`

**Comment by layumi** [comment]
Dear @JoyLuo ,
First of all, thank you for your attention on our work. I am glad to hear that you also work in this field.

The junk files contain two kinds of images. 
1. The mis-detection images. (like background images)
2. The ground truth images in the same camera. For example, if the query image is shot in the 5th camera, we do not regard the ground truth img from 5th camera as what we want. Our target is to spot the person from other cameras. Of course, if you put this into account, it will increase the accuracy. Because the same person under the same camera is usually easy to be recognized.

**Comment by JoyLuo** [comment]
Dear @layumi ,
thanks for you reply, and i agree you view about junkfile.
And the focus is when the real rank1 is mis-detecion images(like background images)，ignore it is the processing method of the code. in fact , i think it should not be ignore, and it should be as a wrong rank.

**Comment by layumi** [comment]
@JoyLuo 
You are right. But there are two reasons that may explain why we do not use the background images. 
    1. These junk images may still contain part of the pedestrian. If the junk contain a part of ground truth image, it will make the comparison unfair.
**2. This is the job for detector, not for re-ID. It is a reasonable assumption that the gallery only contain the pedestrian images without background images.**

P.S. This is only my opinion. I may ask Liang Zheng to  answer you. He made the dataset.

**Comment by JoyLuo** [comment]
@layumi 
thanks very much for you patient and kind reply
